default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_original

development:
  <<: *default

production:
  <<: *default
  host: dpg-cmqv5cq1hbls73fm8eq0-a
  database: s_chatbot
  username: s_chatbot_user
  password: GCqKtoarLJmJ0HzCXTBNLJFnQdxaEmp1
